name: CI_monthly
on:
  push:
    tags: ['*']
  workflow_dispatch:
  schedule:
    - cron: '42 14 23 * *'
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false 
      matrix:
        version:
          - '1.6'
          - 'lts'
          - '1'
          - 'pre'
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        exclude:
          - version: '1.6'
            os: macOS-latest
        include:
          - version: '1.6'
            os: macos-15-intel

    steps:
      - uses: actions/checkout@v7
      - uses: julia-actions/setup-julia@v3
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v3
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
